date:
  regex: '^(\d{2})\.(\d{2})\.(\d{4})$'
  description: 'Дата в формате ДД.ММ.ГГГГ'

number_ip:
  regex: '^\d{6}/\d{2}/\d{5}-ИП$'
  description: 'Формат номера исполнительного производства'

event:
  must_be_in: ["Жалоба", "Заявление", "Отзыв"]
  description: 'Разрешённые типы мероприятий'

adresat:
  must_be_in: ["ФССП", "Сбербанк", "Почта Банк"]
  description: 'Допустимые адресаты'
