date:
  regex: '^(\d{2})\.(\d{2})\.(\d{4})$'
  description: 'Дата в формате ДД.ММ.ГГГГ'

number_ip:
  regex: '^\d{6}/\d{2}/\d{5}-ИП$'
  description: 'Формат номера исполнительного производства'

event:
  must_be_in: ["Жалоба", "Заявление", "Отзыв"]
  description: 'Разрешённые типы мероприятий'

adresat:
  must_be_in: ["ФССП", "Сбербанк", "Почта Банк"]
  description: 'Допустимые адресаты'

barcode:
  # Признаки входящего (скан + служебные идентификаторы ФССП)
  regex_any:
    - '^\s*\d(?:[\s\d]{6,})/\s*\d{2,}\s*$'         # пример: "1 2 1 0 6 8 8 5 2 / 5 9 2 3"
    - '\bИдентификатор ИП:\s*\d+\b'                # служебные блоки идентификаторов
    - '\bВид документа:\s*[A-Z0-9_,-]+'            # строка "Вид документа: ..."
  description: 'Признаки входящего (скан + служебные идентификаторы ФССП)'

direction_detection:
  explicit_keywords:
    outbound: ['исходящ(ее|ий|ая)', 'outgoing', 'outbound']
    inbound: ['входящ(ее|ий|ая)', 'incoming', 'inbound']
  default_direction: 'outbound'
